# Fly.io configuration for SMOL
# See https://fly.io/docs/reference/configuration/

app = "smol-graphs-db"
primary_region = "iad"

[build]

[env]
  DATABASE_URL = "sqlite:////data/smol.db"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source = "smol_data"
  destination = "/data"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
